
export const PRODUCT_IMAGES = [
  "https://picsum.photos/200/200?random=1",
  "https://picsum.photos/200/200?random=2",
  "https://picsum.photos/200/200?random=3",
  "https://picsum.photos/200/200?random=4",
  "https://picsum.photos/200/200?random=5",
];

export const PRODUCT_NAMES = [
  "Luxury Watch Series 5",
  "Smart Home Hub Pro",
  "Designer Leather Bag",
  "Wireless Noise Cancelling Headphones",
  "4K Ultra HD Monitor",
];

export const TRANSLATIONS = {
  en: {
    login: "Login",
    register: "Register",
    home: "Home",
    history: "History",
    start: "Start",
    help: "Help",
    my: "My",
    balance: "Balance",
    deposit: "Deposit",
    withdraw: "Withdraw",
    grab_order: "Grab Order",
    pending: "Pending",
    completed: "Completed",
    success: "Success",
    confirm: "Confirm",
    cancel: "Cancel",
    admin_panel: "Admin Panel",
    welcome: "Welcome back",
    transactions: "Transactions",
    settings: "Settings",
    security: "Security Center",
    logout: "Logout",
    today_orders: "Today's Orders",
    yesterday_commission: "Yesterday Commission",
    total_assets: "Total Assets",
    personal_info: "Personal Information",
    bank_card: "Bank Card",
    security_center: "Security Center",
    dark_mode: "Dark Mode",
    language: "Language",
    linked: "Linked",
    not_linked: "Not Linked",
    edit_info_sub: "Edit Name, Address",
    password_sub: "Password, Info",
    level: "Level",
    commission_rate: "Commission Rate",
    remaining: "Remaining",
    orders: "Orders",
    processing: "Processing...",
    matching: "Matching Merchant...",
    matched: "Order Matched!",
    order_id: "Order ID",
    total_return: "Total Return",
    no_orders: "No orders yet",
    amount: "Amount",
    commission: "Commission",
    submit_order: "Submit Order",
    waiting_system: "Waiting for System...",
    generating_id: "Generating Order ID...",
    success_msg: "Commission added to balance.",
    on: "On",
    off: "Off",
    insufficient_balance_order: "Insufficient balance to process order. Required: ",
    high_value_order_contact_cs: "High order value, please contact customer service.",
    balance_history: "Balance History",
    currency: "Currency",
    quantity: "Quantity",
    discount_amount: "Discount Amount",
    confirm_delivery: "Confirm & Delivery",
    handover: "Handover",
    current_total: "Current Total",
    // Admin Specific
    admin_dashboard: "Dashboard",
    admin_users: "User Management",
    admin_transactions: "Transactions",
    admin_orders: "Order Config",
    admin_invites: "Invite Codes",
    admin_settings: "System Settings",
    total_users: "Total Users",
    pending_deposits: "Pending Deposits",
    pending_withdraws: "Pending Withdrawals",
    recent_registrations: "Recent Registrations",
    level_distribution: "Level Distribution",
    user_info: "User Info",
    network_status: "Network/Status",
    ip_address: "IP Address",
    device_info: "Device Info",
    user_type: "Type",
    real_user: "Real",
    fake_user: "Fake",
    action: "Action",
    edit_user: "Edit User",
    reset_orders: "Reset Orders",
    lock_account: "Lock Account",
    unlock_account: "Unlock Account",
    maintenance_mode: "Maintenance Mode",
    maintenance_desc: "Enable to lock user access. Only Admins can log in.",
    save_settings: "Save Settings",
    generate_code: "Generate Code",
    search_placeholder: "Search code or user...",
    status: "Status",
    created: "Created",
    used_by: "Used By",
    expire: "Expire",
    delete: "Delete",
    approve: "Approve",
    reject: "Reject",
    all: "All",
    deposits: "Deposits",
    withdrawals: "Withdrawals",
    popup_image: "Popup Image URL",
    product_name: "Product Name",
    product_image: "Product Image URL",
    optional: "Optional",
    grab_page_config: "Grab Order Page Config",
    text_size: "Text Size",
    text_color: "Text Color"
  },
  vi: {
    login: "Đăng nhập",
    register: "Đăng ký",
    home: "Trang chủ",
    history: "Lịch sử",
    start: "Bắt đầu",
    help: "Trợ giúp",
    my: "Của tôi",
    balance: "Số dư",
    deposit: "Nạp tiền",
    withdraw: "Rút tiền",
    grab_order: "Nhận đơn hàng",
    pending: "Chờ xử lý",
    completed: "Hoàn tất",
    success: "Thành công",
    confirm: "Xác nhận",
    cancel: "Hủy",
    admin_panel: "Quản trị",
    welcome: "Chào mừng trở lại",
    transactions: "Lịch sử giao dịch",
    settings: "Cài đặt",
    security: "Trung tâm an toàn",
    logout: "Đăng xuất",
    today_orders: "Đơn hôm nay",
    yesterday_commission: "Hoa hồng hôm qua",
    total_assets: "Tổng tài sản",
    personal_info: "Thông tin cá nhân",
    bank_card: "Thẻ ngân hàng",
    security_center: "Trung tâm bảo mật",
    dark_mode: "Chế độ tối",
    language: "Ngôn ngữ",
    linked: "Đã liên kết",
    not_linked: "Chưa liên kết",
    edit_info_sub: "Sửa tên, địa chỉ",
    password_sub: "Mật khẩu, thông tin",
    level: "Cấp độ",
    commission_rate: "Tỷ lệ hoa hồng",
    remaining: "Còn lại",
    orders: "Đơn hàng",
    processing: "Đang xử lý...",
    matching: "Đang tìm kiếm...",
    matched: "Đã tìm thấy đơn!",
    order_id: "Mã đơn",
    total_return: "Tổng thu về",
    no_orders: "Chưa có đơn hàng nào",
    amount: "Số tiền",
    commission: "Hoa hồng",
    submit_order: "Gửi đơn",
    waiting_system: "Đang chờ hệ thống...",
    generating_id: "Đang tạo mã đơn...",
    success_msg: "Hoa hồng đã được cộng vào số dư.",
    on: "Bật",
    off: "Tắt",
    insufficient_balance_order: "Số dư không đủ để xử lý đơn hàng. Yêu cầu: ",
    high_value_order_contact_cs: "Giá trị đơn hàng cao, vui lòng liên hệ bộ phận chăm sóc khách hàng.",
    balance_history: "Lịch sử số dư",
    currency: "Tiền tệ",
    quantity: "Số lượng",
    discount_amount: "Tiền chiết khấu",
    confirm_delivery: "Xác nhận & Bàn giao",
    handover: "Bàn giao",
    current_total: "Tổng hiện tại",
    // Admin Specific
    admin_dashboard: "Bảng điều khiển",
    admin_users: "Quản lý người dùng",
    admin_transactions: "Giao dịch",
    admin_orders: "Cấu hình đơn hàng",
    admin_invites: "Mã mời",
    admin_settings: "Cài đặt hệ thống",
    total_users: "Tổng người dùng",
    pending_deposits: "Đơn nạp chờ duyệt",
    pending_withdraws: "Đơn rút chờ duyệt",
    recent_registrations: "Đăng ký gần đây",
    level_distribution: "Phân bổ cấp độ",
    user_info: "Thông tin người dùng",
    network_status: "Mạng/Trạng thái",
    ip_address: "Địa chỉ IP",
    device_info: "Thiết bị",
    user_type: "Loại",
    real_user: "Người thật",
    fake_user: "Người ảo",
    action: "Hành động",
    edit_user: "Sửa người dùng",
    reset_orders: "Đặt lại đơn hàng",
    lock_account: "Khóa tài khoản",
    unlock_account: "Mở khóa",
    maintenance_mode: "Chế độ bảo trì",
    maintenance_desc: "Bật để khóa truy cập người dùng. Chỉ Admin mới có thể đăng nhập.",
    save_settings: "Lưu cài đặt",
    generate_code: "Tạo mã",
    search_placeholder: "Tìm mã hoặc người dùng...",
    status: "Trạng thái",
    created: "Ngày tạo",
    used_by: "Người dùng",
    expire: "Hết hạn",
    delete: "Xóa",
    approve: "Duyệt",
    reject: "Từ chối",
    all: "Tất cả",
    deposits: "Nạp tiền",
    withdrawals: "Rút tiền",
    popup_image: "URL Ảnh Popup",
    product_name: "Tên Sản phẩm",
    product_image: "URL Ảnh SP",
    optional: "Tùy chọn",
    grab_page_config: "Cấu hình trang Nhận đơn",
    text_size: "Cỡ chữ",
    text_color: "Màu chữ"
  },
  zh: {
    login: "登录",
    register: "注册",
    home: "首页",
    history: "历史",
    start: "开始",
    help: "帮助",
    my: "我的",
    balance: "余额",
    deposit: "充值",
    withdraw: "提现",
    grab_order: "抢单",
    pending: "待处理",
    completed: "已完成",
    success: "成功",
    confirm: "确认",
    cancel: "取消",
    admin_panel: "管理面板",
    welcome: "欢迎回来",
    transactions: "交易记录",
    settings: "设置",
    security: "安全中心",
    logout: "登出",
    today_orders: "今日订单",
    yesterday_commission: "昨日佣金",
    total_assets: "总资产",
    personal_info: "个人信息",
    bank_card: "银行卡",
    security_center: "安全中心",
    dark_mode: "深色模式",
    language: "语言",
    linked: "已关联",
    not_linked: "未关联",
    edit_info_sub: "编辑姓名，地址",
    password_sub: "密码，信息",
    level: "等级",
    commission_rate: "佣金率",
    remaining: "剩余",
    orders: "订单",
    processing: "处理中...",
    matching: "匹配商户中...",
    matched: "订单匹配成功!",
    order_id: "订单号",
    total_return: "总回报",
    no_orders: "暂无订单",
    amount: "金额",
    commission: "佣金",
    submit_order: "提交订单",
    waiting_system: "等待系统...",
    generating_id: "生成订单号...",
    success_msg: "佣金已添加到余额。",
    on: "开",
    off: "关",
    insufficient_balance_order: "余额不足，无法处理订单。 需要：",
    high_value_order_contact_cs: "订单金额过高，请联系客服。",
    balance_history: "余额历史",
    currency: "货币",
    quantity: "数量",
    discount_amount: "折扣金额",
    confirm_delivery: "确认并交付",
    handover: "移交",
    current_total: "当前总计",
    // Admin Specific
    admin_dashboard: "仪表盘",
    admin_users: "用户管理",
    admin_transactions: "交易管理",
    admin_orders: "订单配置",
    admin_invites: "邀请码",
    admin_settings: "系统设置",
    total_users: "总用户",
    pending_deposits: "待处理充值",
    pending_withdraws: "待处理提现",
    recent_registrations: "最近注册",
    level_distribution: "等级分布",
    user_info: "用户信息",
    network_status: "网络/状态",
    ip_address: "IP地址",
    device_info: "设备信息",
    user_type: "类型",
    real_user: "真实",
    fake_user: "虚拟",
    action: "操作",
    edit_user: "编辑用户",
    reset_orders: "重置订单",
    lock_account: "锁定账户",
    unlock_account: "解锁账户",
    maintenance_mode: "维护模式",
    maintenance_desc: "启用以锁定用户访问。仅限管理员登录。",
    save_settings: "保存设置",
    generate_code: "生成代码",
    search_placeholder: "搜索代码或用户...",
    status: "状态",
    created: "创建时间",
    used_by: "使用者",
    expire: "过期",
    delete: "删除",
    approve: "批准",
    reject: "拒绝",
    all: "全部",
    deposits: "充值",
    withdrawals: "提现",
    popup_image: "弹窗图片 URL",
    product_name: "产品名称",
    product_image: "产品图片 URL",
    optional: "可选",
    grab_page_config: "抢单页面配置",
    text_size: "文字大小",
    text_color: "文字颜色"
  }
};
